model:
  checkpoint: ../ckpts/binddm+ours.pt

data:
  name: pl
  path: ../PDBbind_refined_2020
  split: ../PDBbind_refined_2020_pocket10_split.pt

sample:
  seed: 2021
  num_samples: 10
  num_steps: 1000
  pos_only: False
  center_pos_mode: protein
  sample_num_atoms: prior
